# Generated by Django 5.0.12 on 2025-05-04 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='voutes_to_skip',
            new_name='votes_to_skip',
        ),
    ]
